# Generated by Django 6.0.4 on 2026-04-11 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NCMS_USERS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=200)),
                ('User_Password', models.CharField(max_length=250)),
                ('User_Role', models.CharField(max_length=250)),
                ('User_Email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gallery_Title', models.CharField(max_length=300)),
                ('Gallery_Files', models.ImageField(blank=True, null=True, upload_to='Gallery/')),
                ('Gallery_Vedio', models.FileField(blank=True, null=True, upload_to='Vedio/')),
                ('Gallery_Dic', models.TextField(max_length=500)),
                ('Created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coreapp.ncms_users')),
            ],
        ),
        migrations.CreateModel(
            name='NIICS_TEACHERS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_Id', models.CharField(blank=True, default='No Thing', max_length=250, null=True)),
                ('Teacher_Name', models.CharField(max_length=250)),
                ('Teacher_Img', models.ImageField(upload_to='TeacherImg/')),
                ('IsClassTeacher', models.BooleanField(default=False)),
                ('Teacher_User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coreapp.ncms_users')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Add_no', models.CharField(max_length=50, unique=True)),
                ('Student_Name', models.CharField(max_length=250)),
                ('Student_Phone', models.CharField(max_length=15)),
                ('Student_Goal', models.CharField(blank=True, max_length=250, null=True)),
                ('Student_Dob', models.DateField(default='2010-08-10')),
                ('Student_Father', models.CharField(max_length=250)),
                ('Student_Address', models.CharField(max_length=250)),
                ('Student_Img', models.ImageField(upload_to='student_Box/')),
                ('is_Controller', models.BooleanField(blank=True, default=False, null=True)),
                ('Stn_User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coreapp.ncms_users')),
            ],
        ),
        migrations.CreateModel(
            name='Wing_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wing_Code', models.CharField(max_length=50, unique=True)),
                ('Wing_Name', models.CharField(max_length=250, unique=True)),
                ('wing_logo', models.ImageField(upload_to='wing_Box/')),
                ('Total_Registered', models.IntegerField(default=0)),
                ('Total_ReSulted', models.IntegerField(default=0)),
                ('Assist_Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_in_wings', to='coreapp.student_model')),
                ('Chair_Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chairPerson_in_wings', to='coreapp.student_model')),
                ('wing_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coreapp.ncms_users')),
            ],
        ),
    ]
